name: CI
on:
  push:
    branches:
      - main

permissions:
  contents: write # for checkout and publishing a GitHub release
  id-token: write # for generating NPM provenance

jobs:
  release:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Upload coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Build
        run: npx lerna run build

      - name: Configure Git
        run: |
          git config --global user.email "foreverskyin+github@gmail.com"
          git config --global user.name "Foreverskyin0216"

      - name: Version
        run: "npx lerna version -m \"chore(release): publish [skip ci]\" --yes"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish
        run: npx lerna publish from-package --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
